name: landing-preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'sdk/packages/modal/**'

jobs:
  upload:
    runs-on: [testing]
    steps:
      - name: FIX BULLSHIT PERMISSION
        run: |
          echo ${{secrets.TESTING_LAPTOP_PASSWORD}} | sudo -S chown -R $USER:$USER /home/syncomp/runners
          echo ${{secrets.TESTING_LAPTOP_PASSWORD}} | sudo -S chown $(whoami):$(whoami) /var/run/docker.sock
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_NIGHTLY_CONNECT_MODAL_STORYBOOK }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_ORG_ID }}
          PRODUCTION: false
